version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    container_name: api_backend
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    container_name: db_mongo
    volumes: 
      - /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root