version: '3.8'
name: backend-debug-setup
services:
  fastapi-vscode-debug-setup:
      build: ./backend
      ports:
        - 5000:5000
        - 5678:5678
      volumes:
        - ./backend/app:/code/app
      command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload"]
      environment:
        - APP_MESSAGE=Hello debugger   
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app"
      - "/app/node_modules"
    container_name: frontend_react
  database:
      container_name: maria-db-debug
      image: mariadb
      environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: mydatabase
        MYSQL_USER: user
        MYSQL_PASSWORD: password
      volumes:
        - mariadb-data:/var/lib/mysql
      expose:
          - "40000"
      ports:
          - "40000:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306 
    depends_on:
      - database
volumes:
  mariadb-data:
